advcbv/advcbv/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from basic_app import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls', namespace='basic_app')),
]

advcbv/basic_app/templates/basic_app/learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE URLS
app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

advcbv/basic_app/templates/basic_app/learning_users/learning_users/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special'),
]

advcbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views




app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>[-\w]+)/$', views.SchoolDetailView.as_view(),name='detail'),
]

advcbv/basic_app/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=264)
    principal = models.CharField(max_length=128)
    location = models.CharField(max_length=264)

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basic_app/templates/basic_app/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

advcbv/basic_app/templates/basic_app/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

advcbv/basic_app/templates/basic_app/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm


#IMPORT FOR LOGIN
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse('YOU ARE LOGGED IN, VERY NICE')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']


            profile.save()
            registered = True
        else:
                print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/register.html',
                        {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account Not Active')
        else:
            print('Someone tried to login and failed')
            print("username: {} and password {}".format(username, password))
            return HttpResponse('Invalid Details supplied')
    else:
        return render(request, 'basic_app/user_login.html',{})

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView
from . import models


# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School



class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_details.html'

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a>
      <div class="class="collapse navbar-collapse" id="navbarSupportedContent"">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

advcbv/basic_app/templates/basic_app/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
      <div class="class="collapse navbar-collapse" id="navbarSupportedContent"">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:register' %}">REGISTER</a></li>

          {% if user.is_authenticated %}
           <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">LOGOUT</a></li>
           <li class="nav-item"><a class="nav-link" href="{% url 'special' %}">SPECIAL</a></li>
          {% else %}
           <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:user_login' %}">LOGIN</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

advcbv/basic_app/templates/basic_app/learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to index page</h1>
</div>
{% endblock %}

advcbv/basic_app/templates/basic_app/learning_users/templates/basic_app/register.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering with us</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Fill out the registeration form</h3>

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" class="btn btn-primary" value="Register">
    </form>
  {% endif %}
</div>
{% endblock %}

advcbv/basic_app/templates/basic_app/learning_users/templates/basic_app/user_login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome To Login Page</h1>
  <h4>Please Login</h4>
  <form action="{% url 'basic_app:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="enter username">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="enter password">
    <input type="submit" class="btn btn-primary" value="Login">
  </form>
</div>
{% endblock%}

advcbv/basic_app/templates/basic_app/school_details.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>This is the school details page</h1>
  <h2>School Details:</h2>
  <p>Name:{{ school_detail.name }}</p>
  <p>Principal: {{ school_detail.principal }}</p>
  <p>Location: {{ school_detail.location }}</p>

  <h3>Students:</h3>

  {% for student in school_detail.students.all %}
  <p>{{ student.name }} who is {{ student.age }} years old.</p>
  {% endfor %}
</div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
<h1>This is the list of all the schools</h1>
<ol>
  {% for school in schools %}
  <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
  {% endfor %}
</ol>
{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a>
      <div class="class="collapse navbar-collapse" id="navbarSupportedContent"">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

advcbv/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Home Page</h1>
</div>
{% endblock %}